import{a as m,S as b,i}from"./assets/vendor-Dn3QujGD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))t(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&t(h)}).observe(document,{childList:!0,subtree:!0});function a(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(o){if(o.ep)return;o.ep=!0;const s=a(o);fetch(o.href,s)}})();m.defaults.baseURL="https://pixabay.com/api/";async function p(r,e=1){const a={key:"49272449-54e018c7c1ace9d1b8dfc3596",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};try{return(await m.get("",{params:a})).data}catch(t){throw console.error("Error fetching data from Pixabay API:",t),t}}const g=document.querySelector(".gallery");function v(){return new b(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:350})}function y(r,e){const a=r.filter(t=>t.largeImageURL&&t.webformatURL&&t.tags);a.length>0?(g.insertAdjacentHTML("beforeend",a.map(t=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t.largeImageURL}">
        <img
          class="gallery-image"
          src="${t.webformatURL}"
          data-source="${t.largeImageURL}"
          alt="${t.tags}"
        />
      </a>
      <p>Likes: ${t.likes}</p>
      <p>Views: ${t.views}</p>
      <p>Comments: ${t.comments}</p>
      <p>Downloads:  ${t.downloads}</p>
    </li>`).join("")),e&&e.refresh()):console.warn("No valid images to render.")}function S(){g.innerHTML=""}const L=document.querySelector(".form"),d=document.querySelector(".loader"),I=document.querySelector(".gallery"),l=document.querySelector(".js-button");let c="",n=1,f=0,u=v();L.addEventListener("submit",R);l.addEventListener("click",$);async function R(r){if(r.preventDefault(),c=r.currentTarget.elements["search-text"].value.trim(),!!c){d.classList.remove("hidden"),S(),L.reset(),n=1;try{const{hits:e,totalHits:a}=await p(c,n);if(console.log("API Response:",{hits:e,totalHits:a}),!e||e.length===0){i.error({title:"Sorry",message:"No images found, please try another search.",position:"topRight"}),l.classList.add("hidden");return}f=a,y(e,u),u.refresh(),w(e),Math.ceil(f/15)===n?(i.show({title:"End of search",message:"You have reached the end of the collection.",position:"topRight"}),l.classList.add("hidden")):l.classList.remove("hidden")}catch(e){i.error({title:"Error",message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{d.classList.add("hidden")}}}async function $(){if(n*15<f){d.classList.remove("hidden"),n+=1;try{const{hits:r}=await p(c,n);console.log("Hits on load more:",r),r&&r.length>0?(y(r,u),u.refresh(),w(r)):console.warn("No more images found."),Math.ceil(f/15)===n&&(i.show({title:"End of search",message:"You have reached the end of the collection.",position:"topRight"}),l.classList.add("hidden"))}catch(r){i.error({title:"Error",message:`Something went wrong: ${r.message}`,position:"topRight"})}finally{d.classList.add("hidden")}}}function w(r){const e=I.querySelector(".gallery-item:nth-last-child("+r.length+")");e&&e.scrollIntoView({behavior:"smooth",block:"start"})}
//# sourceMappingURL=index.js.map
