import{a as h,S as w,i}from"./assets/vendor-Dn3QujGD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();h.defaults.baseURL="https://pixabay.com/api/";async function p(t,e=1){const n={key:"49272449-54e018c7c1ace9d1b8dfc3596",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};try{return(await h.get("",{params:n})).data}catch(a){throw console.error("Error fetching data from Pixabay API:",a),a}}const m=document.querySelector(".gallery");function b(t){m.insertAdjacentHTML("beforeend",t.map(e=>`
  <li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}">
      <img
        class="gallery-image"
        src="${e.webformatURL}"
        data-source="${e.largeImageURL}"
        alt="${e.tags}"
      />
    </a>
    <p>Likes: ${e.likes}</p>
    <p>Views: ${e.views}</p>
    <p>Comments: ${e.comments}</p>
    <p>Downloads:  ${e.downloads}</p>
  </li>`).join(""))}function v(){m.innerHTML=""}const g=document.querySelector(".form"),c=document.querySelector(".loader"),S=document.querySelector(".gallery"),d=document.querySelector(".js-button");let l="",s=1,u=0;const y=new w(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:350});g.addEventListener("submit",R);d.addEventListener("click",$);async function R(t){if(t.preventDefault(),l=t.currentTarget.elements["search-text"].value.trim(),!!l){c.classList.remove("hidden"),v(),g.reset(),s=1;try{const{hits:e,totalHits:n}=await p(l,s);if(console.log("API Response:",{hits:e,totalHits:n}),!e||e.length===0){i.error({title:"Sorry",message:"No images found, please try another search.",position:"topRight"});return}u=n,L(e),y.refresh(),Math.ceil(u/15)===s?(i.show({title:"End of search",message:"You have reached the end of the collection.",position:"topRight"}),d.classList.add("hidden")):d.classList.remove("hidden")}catch(e){i.error({title:"Error",message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{c.classList.add("hidden")}}}function L(t){Array.isArray(t)&&t.length>0?(console.log("Rendering images:",t),S.insertAdjacentHTML("beforeend",b(t)),y.refresh()):console.warn("No valid images to render.")}async function $(){if(s*15<u){c.classList.remove("hidden"),s+=1;try{const{hits:t}=await p(l,s);console.log("Hits on load more:",t),t&&t.length>0?L(t):console.warn("No more images found."),Math.ceil(u/15)===s&&(i.show({title:"End of search",message:"You have reached the end of the collection.",position:"topRight"}),d.classList.add("hidden"))}catch(t){i.error({title:"Error",message:`Something went wrong: ${t.message}`,position:"topRight"})}finally{c.classList.add("hidden")}}}
//# sourceMappingURL=index.js.map
